version: '3.6'

services:
  ia_config_agent:
    build:
      context: $PWD/../ConfigAgent/agent
      dockerfile: $PWD/../ConfigAgent/agent/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        ETCD_VERSION: ${ETCD_VERSION}
    read_only: false
    image: ia_config_agent:${EII_VERSION}
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    container_name: ia_config_agent
    environment:
      SERVICES: ""
      AppName: "ConfigAgent"
      HOST_IP: $HOST_IP
      HOST_TIME_ZONE: $HOST_TIME_ZONE
      ETCDCTL_API: 3
      DEV_MODE: $DEV_MODE
      ETCD_HOST: $ETCD_HOST
      ETCD_DATA_DIR: $ETCD_DATA_DIR
      ETCD_CLIENT_PORT: $ETCD_CLIENT_PORT
      ETCD_PEER_PORT: $ETCD_PEER_PORT
      ETCD_NAME: $ETCD_NAME
      ETCD_INITIAL_CLUSTER_STATE: $ETCD_INITIAL_CLUSTER_STATE
      ETCD_INITIAL_CLUSTER: $ETCD_INITIAL_CLUSTER
      ETCD_ROOT_PASSWORD: $ETCD_ROOT_PASSWORD
      ETCD_PREFIX: $ETCD_PREFIX
      no_proxy: $eii_no_proxy
      NO_PROXY: $eii_no_proxy
    network_mode: host
    ipc: "none"
    volumes:
      - ./Certificates:/EII/Certificates:rw
      - ./Certificates/root:/EII/Certificates/root
      - ./Certificates/rootca:/EII/Certificates/rootca
