version: '3.6'

services:
  setup:
    image: alpine:latest
    volumes:
      - ./test:/data
    command: >
      ash -c "mkdir -p /data/testing-new-dir &&
                echo \"hello, world!\" > /data/testing-new-dir/hello.txt &&
                echo \"setup done\""

  test:
    depends_on:
      - setup
    image: alpine:latest
    volumes:
      - ./test/testing-new-dir:/data
    command: >
      ash -c "ls /data && cat /data/hello.txt"
